"""empty message

Revision ID: 0342caead282
Revises: ea75bf3207f1
Create Date: 2018-06-12 01:30:33.652607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0342caead282'
down_revision = 'ea75bf3207f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('burgers', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.add_column('toppings', sa.Column('burger_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'toppings', 'burgers', ['burger_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'toppings', type_='foreignkey')
    op.drop_column('toppings', 'burger_id')
    op.alter_column('burgers', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
